# Generated by Django 2.1 on 2020-09-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200901_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='mage',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
